algoritmo "Cambio Creuza"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    reais, dolares: real

inicio

    Escreva ("Quantos reais eu tenho? R$ ")
    Leia(reais)
    dolares <- reais / 5.0
    Escreva ("Meus R$ ", reais, " valem US$ ", dolares)

fimalgoritmo