Algoritmo "Conversor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/27/2023
Var
// Seção de Declarações das variáveis 
 angulo, s:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

    EscrevaL ("Informe um angulo: ")
    Leia(angulo)

    s <- sen(grauprad(angulo))

    EscrevaL ("Seno de ", angulo, " é: ", s)


Fimalgoritmo