Algoritmo "primeiro"
/// Disciplina  :[Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
    msg: caractere
    numInt: inteiro
    numFra: real
    falVer: logico

inicio
    msg <- "Ola Mundo!!!"

    EScrevaL (msg)
    EscrevaL ("Olá, Mundo!!!")
    Escreva ("me livrei da maldição")
fimalgoritmo