Algoritmo "Cambio Creuza"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/21/2023
Var
// Seção de Declarações das variáveis 
   reais, dolares: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva ("Quantos reais eu tenho? R$ ")
   Leia(reais)
   dolares <- reais / 5.0
   Escreva ("Meus R$ ", reais, " valem US$ ", dolares)

Fimalgoritmo